env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
  max-len:
    - error
    - 120
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/explicit-module-boundary-types":
    - off
  "@typescript-eslint/no-empty-interface":
    - off
  
